spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://47.101.33.86:3306/lingyongqian?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
