CREATE TABLE `cl_user_base_info_encrypt` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL COMMENT '客户表 外键',
  `phone_encrypt` varchar(255) DEFAULT NULL COMMENT '手机号码',
  `real_name` varchar(30) DEFAULT NULL COMMENT '真实姓名',
  `age` int(11) DEFAULT '0' COMMENT '年龄 ',
  `sex` varchar(30) DEFAULT NULL COMMENT '性别',
  `national` varchar(30) DEFAULT NULL COMMENT '民族',
  `id_no_encrypt` varchar(255) DEFAULT NULL COMMENT '证件号码',
  `id_addr` varchar(255) DEFAULT NULL COMMENT '身份证地址',
  `living_img` varchar(255) DEFAULT NULL COMMENT '自拍(人脸识别照片)',
  `ocr_img` varchar(255) DEFAULT NULL COMMENT '身份证头像',
  `front_img` varchar(255) DEFAULT NULL COMMENT '身份证正面',
  `back_img` varchar(255) DEFAULT NULL COMMENT '身份证反面',
  `education` varchar(30) DEFAULT NULL COMMENT '学历',
  `marry_state` varchar(30) DEFAULT NULL COMMENT '婚姻状况',
  `company_name` varchar(50) DEFAULT NULL COMMENT '公司名称',
  `company_phone` varchar(32) DEFAULT '' COMMENT '公司电话',
  `company_addr` varchar(255) DEFAULT NULL COMMENT '公司地址',
  `company_detail_addr` varchar(64) DEFAULT NULL COMMENT '公司详细地址',
  `company_coordinate` varchar(100) DEFAULT '' COMMENT '公司坐标(经度,纬度)',
  `salary` varchar(30) DEFAULT NULL COMMENT '月薪范围',
  `working_years` varchar(30) DEFAULT NULL COMMENT '工作年限',
  `working_img` varchar(512) DEFAULT NULL COMMENT '工作照片',
  `live_time` varchar(30) DEFAULT NULL COMMENT '居住时长',
  `live_addr` varchar(255) DEFAULT NULL COMMENT '居住地址',
  `live_detail_addr` varchar(255) DEFAULT NULL COMMENT '居住详细地址',
  `live_coordinate` varchar(100) DEFAULT NULL COMMENT '居住地坐标，(经度,纬度)',
  `phone_server_pwd` varchar(30) DEFAULT NULL COMMENT '运营商服务密码',
  `register_addr` varchar(255) DEFAULT NULL COMMENT '注册地址',
  `register_coordinate` varchar(100) DEFAULT NULL COMMENT '注册地坐标，(经度,纬度)',
  `state` varchar(30) DEFAULT '20' COMMENT '是否黑名单 ，10是20不是',
  `last_overdue_day` int(3) NOT NULL DEFAULT '0' COMMENT '最后逾期天数',
  `max_overdue_day` int(3) unsigned NOT NULL DEFAULT '0' COMMENT '最大一笔还款金额逾期天数',
  `repay_assess` int(2) NOT NULL DEFAULT '0' COMMENT '催收评级:0-无,1-可直接放款,2-还款意愿良好,3-有负债、重新审核,4-拒贷理由充分',
  `black_reason` varchar(255) DEFAULT '' COMMENT '拉黑原因',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `check_code` varchar(255) DEFAULT NULL COMMENT '供融360 淘金云平台使用 手机号+身份证号拼接生成的md5',
  `update_user_id` int(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `index_check_code` (`check_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='脱敏用户详情表'




CREATE TABLE `cl_user_base_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL COMMENT '客户表 外键',
  `phone` varchar(11) DEFAULT NULL COMMENT '手机号码',
  `real_name` varchar(30) DEFAULT NULL COMMENT '真实姓名',
  `age` int(11) DEFAULT '0' COMMENT '年龄 ',
  `sex` varchar(30) DEFAULT NULL COMMENT '性别',
  `national` varchar(30) DEFAULT NULL COMMENT '民族',
  `id_no` varchar(18) DEFAULT NULL COMMENT '证件号码',
  `id_addr` varchar(255) DEFAULT NULL COMMENT '身份证地址',
  `living_img` varchar(255) DEFAULT NULL COMMENT '自拍(人脸识别照片)',
  `ocr_img` varchar(255) DEFAULT NULL COMMENT '身份证头像',
  `front_img` varchar(255) DEFAULT NULL COMMENT '身份证正面',
  `back_img` varchar(255) DEFAULT NULL COMMENT '身份证反面',
  `education` varchar(30) DEFAULT NULL COMMENT '学历',
  `marry_state` varchar(30) DEFAULT NULL COMMENT '婚姻状况',
  `company_name` varchar(50) DEFAULT NULL COMMENT '公司名称',
  `company_phone` varchar(32) DEFAULT '' COMMENT '公司电话',
  `company_addr` varchar(255) DEFAULT NULL COMMENT '公司地址',
  `company_detail_addr` varchar(64) DEFAULT NULL COMMENT '公司详细地址',
  `company_coordinate` varchar(100) DEFAULT '' COMMENT '公司坐标(经度,纬度)',
  `salary` varchar(30) DEFAULT NULL COMMENT '月薪范围',
  `working_years` varchar(30) DEFAULT NULL COMMENT '工作年限',
  `working_img` varchar(512) DEFAULT NULL COMMENT '工作照片',
  `live_time` varchar(30) DEFAULT NULL COMMENT '居住时长',
  `live_addr` varchar(255) DEFAULT NULL COMMENT '居住地址',
  `live_detail_addr` varchar(255) DEFAULT NULL COMMENT '居住详细地址',
  `live_coordinate` varchar(100) DEFAULT NULL COMMENT '居住地坐标，(经度,纬度)',
  `phone_server_pwd` varchar(30) DEFAULT NULL COMMENT '运营商服务密码',
  `register_addr` varchar(255) DEFAULT NULL COMMENT '注册地址',
  `register_coordinate` varchar(100) DEFAULT NULL COMMENT '注册地坐标，(经度,纬度)',
  `state` varchar(30) DEFAULT '20' COMMENT '是否黑名单 ，10是20不是',
  `last_overdue_day` int(3) NOT NULL DEFAULT '0' COMMENT '最后逾期天数',
  `max_overdue_day` int(3) unsigned NOT NULL DEFAULT '0' COMMENT '最大一笔还款金额逾期天数',
  `repay_assess` int(2) NOT NULL DEFAULT '0' COMMENT '催收评级:0-无,1-可直接放款,2-还款意愿良好,3-有负债、重新审核,4-拒贷理由充分',
  `black_reason` varchar(255) DEFAULT '' COMMENT '拉黑原因',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `check_code` varchar(255) DEFAULT NULL COMMENT '供融360 淘金云平台使用 手机号+身份证号拼接生成的md5',
  `update_user_id` int(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone` (`phone`) USING BTREE,
  UNIQUE KEY `id_no` (`id_no`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `index_check_code` (`check_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户详情表'

